//
//  Person.swift
//  DatesExample
//
//  Created by Russell Gordon on 2024-06-12.
//

import Foundation

// Represents a person who has provided their name
struct Person: Identifiable, Codable {
    var id: Int?
    let firstName: String
    let providedDate: Date
    
    // Provide a hint to the Swift compiler
    // when data is decoded from Supabase or
    // encoded and sent to Supabase
    // What column names in the database table map to
    // what property names here in the structure?
    enum CodingKeys: String, CodingKey {
        case id
        case firstName = "first_name"
        case providedDate = "provided_date"
    }
}

// Sample data for the Person structure (sample data generated by ChatGPT)
let examplePeople: [Person] = [
    Person(id: 1, firstName: "Alice", providedDate: Date()),
    Person(id: 2, firstName: "Bob", providedDate: Date()),
    Person(id: 3, firstName: "Charlie", providedDate: Date()),
    Person(id: 4, firstName: "Diana", providedDate: Date()),
    Person(id: 5, firstName: "Evan", providedDate: Date())
]
